name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow-dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: false
